provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'eu-west-2'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::your-bucket-name/*
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"
  
  functions:
  demo:
    timeout: 60
    memorySize: 2048
    image:
      name: img
